name: ci-workflow
on:
    push:
      branches:
        - develop
    pull_request:
      branches:
        - develop
jobs:
     first_job:
      runs-on: ubuntu-latest
      steps:
         - name:  Welcome steps
           run: echo "welcome to github"
         - name: Checkout Repository
           uses:  actions/checkout@v4
         - name: Repository Basic info
           run: |
              echo "Repository Name: ${{github.repository}}"  
              echo "Repository owner: ${{github.owner}}"           
